In [3]:
#import this before other imports
from sklearnex import patch_sklearn,unpatch_sklearn

patch_sklearn()
#unpatch_sklearn()

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)


In [4]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import scipy.stats as stats
import pylab as pl
import seaborn as sns
from urllib.parse import urlparse
from tld import get_tld
import re
from sklearn.model_selection import train_test_split
import seaborn as sb
import warnings
warnings.filterwarnings('ignore')
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.multiclass import OneVsOneClassifier
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import f1_score,log_loss,precision_score,recall_score,make_scorer,accuracy_score
import json
from sklearn.decomposition import TruncatedSVD
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [5]:
from pyrqa.computation import RPComputation
from pyrqa.image_generator import ImageGenerator
from pyrqa.time_series import TimeSeries
from pyrqa.settings import Settings
from pyrqa.analysis_type import Classic
from pyrqa.neighbourhood import FixedRadius
from pyrqa.metric import EuclideanMetric
from pyrqa.computation import RQAComputation

In [6]:
train = pd.read_csv("train_set.csv")
train

url  result
0       http://player.polyv.net/videos/3ee850a192d81e2...       2
1           http://www.hmaca.com/winnipeg-accounting-blog       1
2       http://www.generalcustom.com.br/index.php?opti...       1
3       http://bigcinema.tv/tag/%D0%94%D0%B8%D1%80%D0%...       0
4       http://www.hafenrocker.de/news/119-news-210920...       1
...                                                   ...     ...
132287        http://masterstrans.com/component/contact/1       1
132288  http://www.tvmiros.gr/parousiasi-tou-sxediou-m...       1
132289  https://twitter.com/home?status=%E3%83%8C%E3%8...       0
132290  http://schertzauto.com/wp-content/themes/NAPA%...       2
132291     http://archive.dissent.org.uk/component/option       4

[132292 rows x 2 columns]

In [7]:
valid = pd.read_csv("valid_set.csv")
valid

url  result
0      http://jmrsl.net/index.php?option=com_jevents&...       1
1      http://www.ekwdesign.de/referenzen/corporate-d...       1
2      http://img25.artxun.com/sdd/oldimg/5dfd/5dfd94...       2
3      http://yourdayyourbudget.com/index.php?option=...       1
4      http://www.modconsolas.com/portal/index.php?li...       1
...                                                  ...     ...
16532  http://bisaneema.org/%e0%a4%87%e0%a4%a4%e0%a4%...       2
16533           http://drogheriapreti.com/chi-siamo.html       1
16534  http://otomoto.pl/oferta/renault-trafic-zareje...       0
16535  http://www.bishopstrings.com/violins/ยฃ5000-ยฃ...       1
16536  http://atwiki.jp/wiki/%E6%93%AC%E4%BA%BA%E3%82...       0

[16537 rows x 2 columns]

In [8]:
test = pd.read_csv("test_set.csv")
test

url  result
0      http://www.jin0044.com/cl/?module=System&metho...       2
1             http://bjgdhm.com/show_products.asp?id=433       1
2      http://www.masseny.de/index.php?option=com_pho...       1
3      http://maybank2u.com.my/mbb_info/m2u/public/pe...       0
4      http://yourlust.com/videos/picked-up-whore-kar...       0
...                                                  ...     ...
16532               http://www.lisambiental.com.br/x.txt       1
16533  http://pflegeheim-lausitz.de/index.php?option=...       1
16534  http://www.shekinahphotography.co.za/index.php...       1
16535  http://wddga.com/index.html?limitstart=20&font...       1
16536  http://www.selbsthilfegruppen.at/index.php?opt...       1

[16537 rows x 2 columns]

In [9]:
data=[train,valid,test]
urls = pd.concat(data, ignore_index=True)

In [10]:
urls

url  result
0       http://player.polyv.net/videos/3ee850a192d81e2...       2
1           http://www.hmaca.com/winnipeg-accounting-blog       1
2       http://www.generalcustom.com.br/index.php?opti...       1
3       http://bigcinema.tv/tag/%D0%94%D0%B8%D1%80%D0%...       0
4       http://www.hafenrocker.de/news/119-news-210920...       1
...                                                   ...     ...
165361               http://www.lisambiental.com.br/x.txt       1
165362  http://pflegeheim-lausitz.de/index.php?option=...       1
165363  http://www.shekinahphotography.co.za/index.php...       1
165364  http://wddga.com/index.html?limitstart=20&font...       1
165365  http://www.selbsthilfegruppen.at/index.php?opt...       1

[165366 rows x 2 columns]

In [11]:
vectorizer = CountVectorizer(analyzer='char')
mean_vec = vectorizer.fit_transform(urls['url'])
mean_vec.shape

(165366, 133)

In [17]:
mean_vec[0].todense()

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 2, 2, 3, 3, 0, 4,
         1, 0, 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 7, 6,
         0, 1, 1, 0, 0, 2, 0, 1, 2, 3, 0, 1, 2, 3, 0, 2, 1, 0, 2, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [32]:
data_points = mean_vec[2].todense().tolist()[0]
data_points

[0,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 4,
 3,
 9,
 2,
 3,
 5,
 0,
 6,
 1,
 0,
 0,
 6,
 1,
 0,
 0,
 4,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 9,
 9,
 14,
 11,
 5,
 3,
 3,
 7,
 6,
 7,
 1,
 9,
 11,
 15,
 10,
 13,
 2,
 7,
 8,
 9,
 3,
 9,
 10,
 5,
 5,
 14,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [41]:
#data_points = INPUT
time_series = TimeSeries(data_points,
                         embedding_dimension=2,
                         time_delay=1)
settings = Settings(time_series,
                    analysis_type=Classic,
                    neighbourhood=FixedRadius(0.65),
                    similarity_measure=EuclideanMetric,
                    theiler_corrector=1)
computation = RQAComputation.create(settings,
                                    verbose=True)
result = computation.run()
result.min_diagonal_line_length = 2
result.min_vertical_line_length = 2
result.min_white_vertical_line_length = 2
print(result)

[Platform 'NVIDIA CUDA']
Vendor: NVIDIA Corporation
Version: OpenCL 3.0 CUDA 11.6.127
Profile: FULL_PROFILE
Extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid cl_khr_pci_bus_info cl_khr_external_semaphore cl_khr_external_memory cl_khr_external_semaphore_win32 cl_khr_external_memory_win32


[Device 'NVIDIA GeForce GTX 1060']
Vendor: NVIDIA Corporation
Type: 4
Version: OpenCL 3.0 CUDA
Profile: FULL_PROFILE
Max Clock Frequency: 1733
Global Mem Size: 6442254336
Address Bits: 64
Max Compute Units: 10
Max Work Group Size: 1024
Max Work Item Dimensions: 3
Max Work

In [34]:
computation = RPComputation.create(settings)
result = computation.run()
ImageGenerator.save_recurrence_plot(result.recurrence_matrix_reverse,
                                    'recurrence_plot2.png')

In [68]:
url_vec = []
mean = []
std = []
skew = []
kurtosis = []
rr = []
det = []
l = []
l_max = []
div = []
l_entr = []
lam = []
tt = []
v_max = []
v_entr = []
w = []
w_max = []
w_entr = []
det_rr = []
lam_det = []
for i in range(0,165366):
    ex = mean_vec[i].todense()
    mean.append(np.mean(ex))
    std.append(np.std(ex))
    skew.append(stats.skew(ex.tolist()[0]))
    kurtosis.append(stats.kurtosis(ex.tolist()[0]))
    url_vec.append(ex.tolist()[0])
    data_points = ex.tolist()[0]
    time_series = TimeSeries(data_points,embedding_dimension=2,time_delay=1)
    settings = Settings(time_series,analysis_type=Classic,neighbourhood=FixedRadius(0.65),similarity_measure=EuclideanMetric,theiler_corrector=1)
    computation = RQAComputation.create(settings)
    result = computation.run()
    result.min_diagonal_line_length = 2
    result.min_vertical_line_length = 2
    result.min_white_vertical_line_length = 2
    rr.append(result.recurrence_rate)
    det.append(result.determinism)
    l.append(result.average_diagonal_line)
    l_max.append(result.longest_diagonal_line)
    div.append(result.divergence)
    l_entr.append(result.entropy_diagonal_lines)
    lam.append(result.laminarity)
    tt.append(result.trapping_time)
    v_max.append(result.longest_vertical_line)
    v_entr.append(result.entropy_vertical_lines)
    w.append(result.average_white_vertical_line)
    w_max.append(result.longest_white_vertical_line)
    w_entr.append(result.entropy_white_vertical_lines)
    det_rr.append(result.ratio_determinism_recurrence_rate)
    lam_det.append(result.ratio_laminarity_determinism)
    if i%1000==0:
        print(i/1000)

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0
20.0
21.0
22.0
23.0
24.0
25.0
26.0
27.0
28.0
29.0
30.0
31.0
32.0
33.0
34.0
35.0
36.0
37.0
38.0
39.0
40.0
41.0
42.0
43.0
44.0
45.0
46.0
47.0
48.0
49.0
50.0
51.0
52.0
53.0
54.0
55.0
56.0
57.0
58.0
59.0
60.0
61.0
62.0
63.0
64.0
65.0
66.0
67.0
68.0
69.0
70.0
71.0
72.0
73.0
74.0
75.0
76.0
77.0
78.0
79.0
80.0
81.0
82.0
83.0
84.0
85.0
86.0
87.0
88.0
89.0
90.0
91.0
92.0
93.0
94.0
95.0
96.0
97.0
98.0
99.0
100.0
101.0
102.0
103.0
104.0
105.0
106.0
107.0
108.0
109.0
110.0
111.0
112.0
113.0
114.0
115.0
116.0
117.0
118.0
119.0
120.0
121.0
122.0
123.0
124.0
125.0
126.0
127.0
128.0
129.0
130.0
131.0
132.0
133.0
134.0
135.0
136.0
137.0
138.0
139.0
140.0
141.0
142.0
143.0
144.0
145.0
146.0
147.0
148.0
149.0
150.0
151.0
152.0
153.0
154.0
155.0
156.0
157.0
158.0
159.0
160.0
161.0
162.0
163.0
164.0
165.0


In [69]:
total = np.column_stack((url_vec, mean, std, skew, kurtosis,rr,det,l,l_max,div,l_entr,lam,tt,v_max,v_entr,w,w_max,w_entr,det_rr,lam_det,))

In [83]:
# SAVE TOTAL
#np.save('count&rqa.npy', total)

In [12]:
total1 = np.load('count&rqa.npy')
total1

array([[0.        , 0.        , 0.        , ..., 2.55248904, 1.97579268,
        1.00524996],
       [0.        , 0.        , 0.        , ..., 2.21615601, 1.53406784,
        1.01029084],
       [0.        , 0.        , 0.        , ..., 2.33238268, 2.31857385,
        1.01936198],
       ...,
       [0.        , 0.        , 0.        , ..., 2.4799881 , 2.12994827,
        1.02709983],
       [0.        , 0.        , 0.        , ..., 2.05089712, 1.83534055,
        1.0292002 ],
       [0.        , 0.        , 0.        , ..., 2.50776911, 2.18341935,
        1.0194191 ]])

In [16]:
total1.shape

(165366, 152)

In [17]:
total1[0]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 3.00000000e+00, 4.00000000e+00, 2.00000000e+00,
       2.00000000e+00, 3.00000000e+00, 3.00000000e+00, 0.00000000e+00,
       4.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+00,
       2.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       2.00000000e+00, 1.00000000e+00, 1.00000000e+00, 2.00000000e+00,
       7.00000000e+00, 6.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00,
      

In [13]:
total2 = np.delete(total1, [133,134,135,136], axis=1)

In [15]:
total2.shape

(165366, 148)

In [18]:
total2[0]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 3.00000000e+00, 4.00000000e+00, 2.00000000e+00,
       2.00000000e+00, 3.00000000e+00, 3.00000000e+00, 0.00000000e+00,
       4.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+00,
       2.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       2.00000000e+00, 1.00000000e+00, 1.00000000e+00, 2.00000000e+00,
       7.00000000e+00, 6.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00,
      

In [19]:
train_vec, test_vec = total2[:148829,:], total2[148829:,:]

In [20]:
train_vec.shape

(148829, 148)

In [21]:
test_vec.shape

(16537, 148)

In [22]:
data=[train,valid]
train = pd.concat(data, ignore_index=True)

In [23]:
rf = RandomForestClassifier(random_state = 0, verbose = 10, n_jobs = -1)
rf.fit(train_vec, train['result'])

RandomForestClassifier(n_jobs=-1, random_state=0, verbose=10)

In [24]:
train_pred = rf.predict(train_vec)

In [25]:
test_pred = rf.predict(test_vec)

In [26]:
print("Train Accuracy: ", accuracy_score(train_pred,train['result']))
print("Train Precision: ", precision_score(train_pred,train['result'], average = 'weighted'))
print("Train Recall: ", recall_score(train_pred,train['result'], average = 'weighted'))
print("Train F1: ", f1_score(train_pred,train['result'], average = 'weighted'))
print("Test Accuracy: ", accuracy_score(test_pred,test['result']))
print("Test Precision: ", precision_score(test_pred,test['result'], average = 'weighted'))
print("Test Recall: ", recall_score(test_pred,test['result'], average = 'weighted'))
print("Test F1: ", f1_score(test_pred,test['result'], average = 'weighted'))

Train Accuracy:  1.0
Train Precision:  1.0
Train Recall:  1.0
Train F1:  1.0
Test Accuracy:  0.9784120457156679
Test Precision:  0.9811986348963926
Test Recall:  0.9784120457156679
Test F1:  0.9791611585491242


In [27]:
svm = SVC(random_state = 0, verbose = 10, C = 1, kernel = 'linear')
svm.fit(train_vec, train['result'])

SVC(C=1, kernel='linear', random_state=0, verbose=10)

In [28]:
train_pred = svm.predict(train_vec)

In [29]:
test_pred = svm.predict(test_vec)

In [30]:
print("Train Accuracy: ", accuracy_score(train_pred,train['result']))
print("Train Precision: ", precision_score(train_pred,train['result'], average = 'weighted'))
print("Train Recall: ", recall_score(train_pred,train['result'], average = 'weighted'))
print("Train F1: ", f1_score(train_pred,train['result'], average = 'weighted'))
print("Test Accuracy: ", accuracy_score(test_pred,test['result']))
print("Test Precision: ", precision_score(test_pred,test['result'], average = 'weighted'))
print("Test Recall: ", recall_score(test_pred,test['result'], average = 'weighted'))
print("Test F1: ", f1_score(test_pred,test['result'], average = 'weighted'))

Train Accuracy:  0.8987428525354602
Train Precision:  0.9229727947236441
Train Recall:  0.8987428525354602
Train F1:  0.9066030826313591
Test Accuracy:  0.8960512789502328
Test Precision:  0.9216399466471153
Test Recall:  0.8960512789502328
Test F1:  0.9044792099845124


## Cross-Validation

In [27]:
#metrics
scoring = {'accuracy': make_scorer(accuracy_score),
           'precision': make_scorer(precision_score, average = 'weighted'),
           'recall': make_scorer(recall_score, average = 'weighted'),
           'f1': make_scorer(f1_score, average = 'weighted')}

In [28]:
clf = RandomForestClassifier(n_jobs = -1)

In [29]:
scores = cross_validate(clf, total2, np.array(urls['result'].tolist()), cv=5,scoring=scoring,return_train_score=True)
scores

{'fit_time': array([12.48163247, 12.5523088 , 10.78830957, 11.37921739, 10.69967222]),
 'score_time': array([0.24534559, 0.25431514, 0.2841785 , 0.24438167, 0.25031877]),
 'test_accuracy': array([0.97611417, 0.97487376, 0.97417833, 0.97629486, 0.9756599 ]),
 'train_accuracy': array([0.99998488, 0.99998488, 0.99999244, 0.99996221, 0.99998488]),
 'test_precision': array([0.97618625, 0.97497541, 0.97430649, 0.97642207, 0.97565181]),
 'train_precision': array([0.99998488, 0.99998488, 0.99999244, 0.99996221, 0.99998488]),
 'test_recall': array([0.97611417, 0.97487376, 0.97417833, 0.97629486, 0.9756599 ]),
 'train_recall': array([0.99998488, 0.99998488, 0.99999244, 0.99996221, 0.99998488]),
 'test_f1': array([0.97518456, 0.97383167, 0.97288509, 0.9753005 , 0.97472447]),
 'train_f1': array([0.99998488, 0.99998488, 0.99999244, 0.9999622 , 0.99998488])}

In [30]:
print("The Fit Time is: ",scores['fit_time'].mean())
print("\n")
print("The Score Time is: ",scores['score_time'].mean())
print("\n")
print("The Train Accuracy score is: ",scores['train_accuracy'].mean())
print("\n")
print("The Train F1 score is: ",scores['train_f1'].mean())
print("\n")
print("The Train Precision score is: ",scores['train_precision'].mean())
print("\n")
print("The Train Recall score is: ",scores['train_recall'].mean())
print("\n")
print("The Test Accuracy score is: ",scores['test_accuracy'].mean())
print("\n")
print("The Test F1 score is: ",scores['test_f1'].mean())
print("\n")
print("The Test Precision score is: ",scores['test_precision'].mean())
print("\n")
print("The Test Recall score is: ",scores['test_recall'].mean())
print("\n")

The Fit Time is:  11.580228090286255


The Score Time is:  0.2557079315185547


The Train Accuracy score is:  0.9999818584277052


The Train F1 score is:  0.999981857785896


The Train Precision score is:  0.9999818589209916


The Train Recall score is:  0.9999818584277052


The Test Accuracy score is:  0.9754242063667146


The Test F1 score is:  0.9743852570367968


The Test Precision score is:  0.9755084069128894


The Test Recall score is:  0.9754242063667146




In [31]:
# Above is best as without rqa scores in range of 90%
# ONLY RQA features

In [32]:
total3 = np.delete(total1, [i for i in range(0,137)], axis=1)

In [33]:
total3[0]

array([4.91850321e-01, 9.71794264e-01, 1.55303030e+01, 7.00000000e+01,
       1.42857143e-02, 2.84990740e+00, 9.76896149e-01, 3.03333333e+01,
       7.10000000e+01, 1.09861231e+00, 2.09810427e+01, 1.18000000e+02,
       2.55248904e+00, 1.97579268e+00, 1.00524996e+00])

In [34]:
total3.shape

(165366, 15)

In [35]:
clf = RandomForestClassifier(n_jobs = -1)

In [36]:
scores = cross_validate(clf, total3, np.array(urls['result'].tolist()), cv=5,scoring=scoring,return_train_score=True)
scores

{'fit_time': array([3.55923367, 3.38194895, 3.58564639, 3.34832072, 3.23704147]),
 'score_time': array([0.19946289, 0.15673923, 0.16057396, 0.1835084 , 0.1486578 ]),
 'test_accuracy': array([0.88326178, 0.88461887, 0.88398391, 0.88492123, 0.88250234]),
 'train_accuracy': array([0.99845796, 0.99845041, 0.99850332, 0.99831435, 0.99847309]),
 'test_precision': array([0.88187204, 0.88332837, 0.88216212, 0.88346795, 0.88082985]),
 'train_precision': array([0.99845938, 0.9984519 , 0.99850471, 0.99831584, 0.99847456]),
 'test_recall': array([0.88326178, 0.88461887, 0.88398391, 0.88492123, 0.88250234]),
 'train_recall': array([0.99845796, 0.99845041, 0.99850332, 0.99831435, 0.99847309]),
 'test_f1': array([0.87736086, 0.87908031, 0.8780949 , 0.87897524, 0.87705084]),
 'train_f1': array([0.99845686, 0.99844939, 0.99850249, 0.99831332, 0.99847239])}

In [37]:
print("The Fit Time is: ",scores['fit_time'].mean())
print("\n")
print("The Score Time is: ",scores['score_time'].mean())
print("\n")
print("The Train Accuracy score is: ",scores['train_accuracy'].mean())
print("\n")
print("The Train F1 score is: ",scores['train_f1'].mean())
print("\n")
print("The Train Precision score is: ",scores['train_precision'].mean())
print("\n")
print("The Train Recall score is: ",scores['train_recall'].mean())
print("\n")
print("The Test Accuracy score is: ",scores['test_accuracy'].mean())
print("\n")
print("The Test F1 score is: ",scores['test_f1'].mean())
print("\n")
print("The Test Precision score is: ",scores['test_precision'].mean())
print("\n")
print("The Test Recall score is: ",scores['test_recall'].mean())
print("\n")

The Fit Time is:  3.4224382400512696


The Score Time is:  0.16978845596313477


The Train Accuracy score is:  0.9984398244169481


The Train F1 score is:  0.998438889377241


The Train Precision score is:  0.9984412789859674


The Train Recall score is:  0.9984398244169481


The Test Accuracy score is:  0.8838576285079878


The Test F1 score is:  0.8781124285817906


The Test Precision score is:  0.882332066387711


The Test Recall score is:  0.8838576285079878


